Write something about ETS

Write something about GPS data

In [3]:
# Load Python modules
import matplotlib.pyplot as plt
import numpy as np
import DWT
%matplotlib inline

In [4]:
# Choice of station
station = 'PGC5'
direction = 'lon'
dataset = 'detrended'
filename = '../data/PANGA/' + dataset + '/' + station + '.' + direction

In [5]:
# Look for gaps in data
days = 2
data = np.loadtxt(filename, skiprows=26)
time = data[:, 0]
disp = data[:, 1]
dt = np.diff(time)
gap = np.where(dt > days / 365.0 + 0.001)
print(time[gap])
print(gap)

[2001.38809 2002.05339 2002.09446 2002.68857 2006.90212 2014.90212
 2017.20192]
(array([ 338,  577,  578,  655, 2189, 5102, 5937]),)


In [6]:
# Select a subset of the data without big gaps
ibegin = 2189
iend = 5102
time_sub = time[ibegin + 1 : iend + 1]
disp_sub = time[ibegin + 1 : iend + 1]

In [9]:
# Get all the gaps in the time vector, and insert additional values
dt = np.diff(time_sub)
gap = np.where(dt > 1.0 / 365.0 + 0.001)
time_keep = np.copy(time_sub)
for i in range(0, np.shape(gap)[1]):
    new_time = np.insert(time_sub, gap[i] + 1, )

(array([ 752,  753, 1763, 2143, 2460, 2637]),)

In [12]:
dt[gap]

array([0.00548, 0.00548, 0.00548, 0.00548, 0.00547, 0.00547])

In [ ]:
values = np.arange(1.0 / 365.0, )